---
kind: Service
apiVersion: v1
metadata:
  name: bosh-external
  namespace: bosh
  labels:
    bosh.cloudfoundry.org/deployment: bosh
spec:
  selector:
    bosh.cloudfoundry.org/deployment: bosh
  ports:
    - name: create-env
      port: 6868
      targetPort: 6868
      nodePort: 31000
    - name: director
      port: 25555
      targetPort: 25555
      nodePort: 31001
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31002
    - name: uaa
      port: 8443
      targetPort: 8443
      nodePort: 31003
    - name: config-server
      port: 8844
      targetPort: 8844
      nodePort: 31004
  type: NodePort